public_gsheets_url = "https://docs.google.com/spreadsheets/d/1vGXb4kdq06wOmYkBpCkQ4W-lTXKR5cyY-Q1cdb6Dua8/edit#gid=0"
[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1vGXb4kdq06wOmYkBpCkQ4W-lTXKR5cyY-Q1cdb6Dua8/edit#gid=0"
